service:
  name: "Camunda8Worker"
  description: "Worker service for interacting with Camunda 8 via gRPC API"
  version: "1.0.0"
  dependencies:
    - name: "grpc"
      version: "^1.0.0"
  grpc:
    host: "localhost"
    port: 26500
    proto-files:
      - "camunda8.proto"